    name: my_streamlit_env
    channels:
      - conda-forge
    dependencies:
      - python=3.11
      - pip
      - pip:
        - streamlit==1.26.0
        - face_recognition==1.3.0
        - dlib-bin==19.24.0

        
